export const SET_TOKEN = 'SET_TOKEN';
export const IS_AUTHENTICATED = 'IS_AUTHENTICATED';
export const SET_ALERT = 'SET_ALERT';
export const ALERT_TYPE = {
  SUCCESS: 'ALERT_SUCCESS',
  ERROR: 'ALERT_ERROR',
  CLEAR: 'ALERT_CLEAR'
}
